version: '3.5'

services:
  uploading-files-web:
    container_name: uploading-files-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - "1000:80"
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - uploading-files-be
    networks:
      - uploading-files-network

  uploading-files-be:
    container_name: uploading-files-be
    build:
      context: docker/php/7.1
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=uploading-files
    networks:
      - uploading-files-network

  uploading-files-db:
    container_name: uploading-files-db
    build:
      context: ./docker/database
    ports:
      - "10000:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - uploading-files-db-data:/var/lib/mysql
    networks:
      - uploading-files-network
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  uploading-files-db-data:

networks:
  uploading-files-network:
    external: true
